version: 2.1

parameters:
  run-web:
    type: boolean
    default: false

jobs:
  build-web:
    # Build node project
    docker:
      - image: cimg/node:20.12.2
    working_directory: ~/project/web
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          name: Restore npm cache
          keys:
            - node-deps-v1-{{ checksum "package-lock.json" }}
            - node-deps-v1-
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          name: Save npm cache
          key: node-deps-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Inject environment variables
          command: |
            echo "NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}" > .env
            echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}" >> .env
      - run:
          command: npm run build
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      # Copy output to artifacts dir
      - run:
          name: Copy artifacts
          command: cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: node-build

  deploy:
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  web:
    when: << pipeline.parameters.run-web >>
    jobs:
      - build-web
